{% set name = "cacheyou" %}
{% set version = "23.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cacheyou-{{ version }}.tar.gz
  sha256: 7e408f15f4978fea2247734b308621f75f7fe169b461679519c72e8a85d61d5d

build:
  entry_points:
    - doesitcache = cacheyou._cmd:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pdm-backend
    - pip
  run:
    - python >=3.7
    - msgpack-python >=0.5.2
    - requests

test:
  imports:
    - cacheyou
  commands:
    - pip check
    - doesitcache --help
  requires:
    - pip

about:
  home: https://github.com/frostming/cacheyou
  summary: httplib2 caching for requests
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - daylinmorgan
